export const SITE_CONFIG = {
  name: process.env.NEXT_PUBLIC_SITE_NAME || "Li'L Caca",
  title: process.env.NEXT_PUBLIC_SITE_TITLE || "Li'L Caca | Creative Handcrafted Items",
  description: process.env.NEXT_PUBLIC_SITE_DESCRIPTION || 'Exclusive collection of handwoven necklaces and bracelets meticulously handcrafted for a timeless, editorial look.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000',
  ogImage: process.env.NEXT_PUBLIC_SITE_OG_IMAGE || '/images/aquamarine.png',
  links: {
    facebook: process.env.NEXT_PUBLIC_FACEBOOK_LINK || '#',
    instagram: process.env.NEXT_PUBLIC_INSTAGRAM_LINK || '#',
    whatsapp: process.env.NEXT_PUBLIC_WHATSAPP_LINK || 'https://wa.me/639162291365',
    email: 'e.luis.pelaez@gmail.com',
  },
  keywords: [
    // --- English Set 1 ---
    'handcrafted jewelry', 'handwoven necklace', 'artisan bracelets', 'joulery', 'creative handcrafted items',
    'handmade jewelry', 'artisanal jewelry', 'boho jewelry', 'minimalist jewelry', 'luxury jewelry', 'ethical jewelry', 'sustainable jewelry', 'fair trade jewelry',
    'statement necklace', 'pendant necklace', 'choker necklace', 'beaded necklace', 'woven necklace', 'silk necklace',
    'cuff bracelet', 'bangle bracelet', 'charm bracelet', 'beaded bracelet', 'woven bracelet', 'friendship bracelet',
    'aquamarine jewelry', 'obsidian jewelry', 'quartz jewelry', 'amethyst jewelry', 'crystal jewelry', 'gemstone jewelry',
    'silver jewelry', 'gold jewelry', 'rose gold jewelry', '925 silver', 'gold filled', 'brass jewelry',
    'pearl jewelry', 'freshwater pearls', 'shell jewelry', 'native jewelry',
    'island jewelry', 'tropical jewelry', 'beach jewelry', 'summer jewelry', 'resort wear accessories', 'fashion jewelry',
    'unique gifts', 'birthday gifts', 'anniversary gifts', 'bridesmaid gifts', 'personalized jewelry', 'custom jewelry',
    'commissioned jewelry', 'artisan made', 'locally made',
    'weaving tradition', 'handweaving', 'textile jewelry', 'cord necklace', 'macrame jewelry', 'knotted jewelry',
    'contemporary jewelry', 'avant garde jewelry', 'editorial jewelry', 'runway accessories', 'jewelry design',
    'independent designer', 'boutique jewelry', 'online jewelry store', 'shop jewelry', 'buy jewelry online', 'jewelry collection',
    'limited edition jewelry', 'one of a kind jewelry', 'exclusive jewelry', 'premium jewelry', 'high end jewelry', 'affordable luxury',
    'jewelry branding', 'jewelry marketing', 'jewelry photography', 'jewelry style', 'how to style jewelry', 'jewelry trends 2026',
    "li'l caca collection", "li'l caca shop", "li'l caca accessories", "li'l caca brand", "li'l caca international",

    // --- Aesthetic & Style ---
    'alahas', 'kwintas', 'pulseras', 'hikaw', 'singsing', 'ginto', 'pilak', 'perlas', 'hiyas', 'mutya', 'yaman',
    'gawang kamay', 'hinabi', 'likhang sining', 'tradisyonal', 'kultura', 'pamana', 
    'mula sa puso', 'kayamanan ng dagat', 'biyaya ng kalikasan', 'batong kristal', 'batong itim', 'obsidyano', 'amethyst na hiyas',
    'magandang alahas', 'regalo para sa kanya', 
    'damit at alahas', 'suot na sining', 'makulay na hinabi', 'matibay na kwintas',
    'pulseras na gawa sa kamay', 'regalo sa kaarawan', 'regalo sa anibersaryo', 'pangkasal na alahas', 'abay na alahas',
    'natatanging disenyo', 'sariling disenyo', "likhang li'l caca", "tatak li'l caca", 
    'alahas ng dagat', 'alahas ng bundok', 'katutubong sining', 'habing kamay',
    'sinulid at hiyas', 'kristal na puti', 'kristal na lila', 'kristal na asul', 'alahas na pambabae',
    'alahas na panlalaki', 'regalo para sa nanay', 'regalo para sa asawa', 'regalo para sa kasintahan', 'murang alahas',
    'mamahaling alahas', 'eleganteng alahas', 'simpleng alahas', 'modernong alahas', 'tradisyonal na disenyo',
    'likha ng kamay', 'sining ng paghabi', 'paghabi ng pangarap', "li'l caca accessories",
    'alahas na may kahulugan', 'alahas na may kwento', 'kwento ng artisan', 'suportahan ang lokal', 'bili ng lokal',
    'online shop', 'tindahan ng alahas', 'tindahan ng kwintas', 'tindahan ng pulseras', 'mura at magandang alahas',
    'de-kalidad na alahas', 'totoong ginto', 'totoong pilak', 'totoong perlas', 'alahas na matibay', 'palamuti sa katawan',
    'sining na naisusuot', 'hiyas ng katimugan', 'hiyas ng hilaga', 'hiyas ng gitna', "perlas ng li'l caca",

    // --- English Set 2 (100+) ---
    'luxury lifestyle', 'editorial fashion', 'vogue jewelry', 'harpers bazaar jewelry', 'jewelry addict', 'jewelry lover',
    'jewelry obsessed', 'daily jewelry', 'layering necklaces', 'stackable bracelets', 'arm party', 'neck mess',
    'jewelry organizer', 'jewelry care', 'jewelry cleaning', 'ethical sourcing', 'conflict free gems', 'earth friendly jewelry',
    'small business jewelry', 'women owned business', 'female founder', 'artisan story', 'maker movement', 'slow fashion',
    'conscious consumer', 'capsule wardrobe jewelry', 'timeless elegance', 'vintage inspired', 'retro style jewelry',
    'futuristic jewelry', 'bold aesthetic', 'soft girl aesthetic', 'clean girl aesthetic', 'cottagecore jewelry',
    'dark academia jewelry', 'coastal grandmother jewelry', 'barbiecore jewelry', 'mermaids jewelry', 'ocean inspired',
    'nature inspired jewelry', 'floral jewelry', 'celestial jewelry', 'zodiac jewelry', 'birthstone jewelry',
    'protective crystals', 'healing stones', 'energy jewelry', 'meditation beads', 'yoga jewelry', 'spiritual jewelry',
    'wellness accessories', 'meaningful gifts', 'keepsake jewelry', 'heirloom quality', 'bespoke jewelry',
    'jewelry for her', 'jewelry for him', 'unisex jewelry', 'gender neutral accessories', 'travel jewelry',
    'lightweight jewelry', 'comfort fit', 'hypoallergenic jewelry', 'nickel free', 'sensitive skin jewelry',
    'wedding guest jewelry', 'graduation gift', 'mothers day gift', 'fathers day gift', 'valentines day gift',
    'christmas jewelry', 'holiday sparkle', 'new year jewelry', 'party accessories', 'festival jewelry',
    'rave jewelry', 'concert outfit jewelry', 'brunch style', 'work wear jewelry', 'office accessories',
    'zoom call jewelry', 'statement pieces', 'everyday luxury', 'affordable sparkle', 'investment jewelry',
    'jewelry collection launch', 'new arrivals jewelry', 'best selling jewelry', 'customer favorite jewelry',
    'top rated jewelry', 'jewelry reviews', 'jewelry unboxing', 'jewelry haul', 'jewelry flatlay',
    'jewelry photoshoot', 'jewelry videography', 'jewelry content creator', 'jewelry influencer', 'jewelry blogger',
    'jewelry styling tips', 'how to wear necklaces', 'how to wear bracelets', 'jewelry gift guide', 'luxury gifting'
  ],
};
