export const SITE_CONFIG = {
  name: 'JOULERY',
  title: 'JOULERY | Creative Handcrafted Items',
  description: 'Exclusive collection of handwoven necklaces and bracelets from the Philippines. Crafted in the Philippines for the love of the game.',
  url: 'https://joulery.com',
  ogImage: '/images/aquamarine.png',
  links: {
    facebook: '#',
    instagram: '#',
    whatsapp: 'https://wa.me/639162291365',
    email: 'abrerajuliecca@gmail.com',
  },
  keywords: [
    // --- English Set 1 ---
    'handcrafted jewelry', 'philippines jewelry', 'handwoven necklace', 'artisan bracelets', 'joulery', 'creative handcrafted items',
    'handmade jewelry', 'artisanal jewelry', 'filipino jewelry', 'manila jewelry', 'cebu jewelry', 'palawan jewelry',
    'boho jewelry', 'minimalist jewelry', 'luxury jewelry', 'ethical jewelry', 'sustainable jewelry', 'fair trade jewelry',
    'statement necklace', 'pendant necklace', 'choker necklace', 'beaded necklace', 'woven necklace', 'silk necklace',
    'cuff bracelet', 'bangle bracelet', 'charm bracelet', 'beaded bracelet', 'woven bracelet', 'friendship bracelet',
    'aquamarine jewelry', 'obsidian jewelry', 'quartz jewelry', 'amethyst jewelry', 'crystal jewelry', 'gemstone jewelry',
    'silver jewelry', 'gold jewelry', 'rose gold jewelry', '925 silver', 'gold filled', 'brass jewelry',
    'pearl jewelry', 'freshwater pearls', 'south sea pearls', 'shell jewelry', 'native jewelry', 'tribal jewelry',
    'island jewelry', 'tropical jewelry', 'beach jewelry', 'summer jewelry', 'resort wear accessories', 'fashion jewelry',
    'unique gifts', 'birthday gifts', 'anniversary gifts', 'bridesmaid gifts', 'personalized jewelry', 'custom jewelry',
    'commissioned jewelry', 'artisan made', 'locally made', 'made in philippines', 'proudly filipino', 'filipino craftsmanship',
    'weaving tradition', 'handweaving', 'textile jewelry', 'cord necklace', 'macrame jewelry', 'knotted jewelry',
    'modern filipina', 'contemporary jewelry', 'avant garde jewelry', 'editorial jewelry', 'runway accessories', 'jewelry design',
    'independent designer', 'boutique jewelry', 'online jewelry store', 'shop jewelry', 'buy jewelry online', 'jewelry collection',
    'limited edition jewelry', 'one of a kind jewelry', 'exclusive jewelry', 'premium jewelry', 'high end jewelry', 'affordable luxury',
    'jewelry branding', 'jewelry marketing', 'jewelry photography', 'jewelry style', 'how to style jewelry', 'jewelry trends 2026',
    'joulery collection', 'joulery shop', 'joulery accessories', 'joulery brand', 'joulery ph', 'joulery international',

    // --- Tagalog Set (100+) ---
    'alahas', 'kwintas', 'pulseras', 'hikaw', 'singsing', 'ginto', 'pilak', 'perlas', 'hiyas', 'mutya', 'yaman',
    'gawang kamay', 'hinabi', 'likhang sining', 'katutubo', 'tradisyonal', 'kultura', 'pamana', 'sining ng pilipinas',
    'gawang pinoy', 'tangkilikin ang sariling atin', 'lokal na gawa', 'mula sa puso', 'pinoy pride', 'filipino pride',
    'kayamanan ng dagat', 'biyaya ng kalikasan', 'batong kristal', 'batong itim', 'obsidyano', 'amethyst na hiyas',
    'perlas ng silangan', 'perlas ng pilipinas', 'magandang alahas', 'regalo para sa kanya', 'pasalubong galing pinoy',
    'damit at alahas', 'estilong pinoy', 'pormang pinoy', 'suot na sining', 'makulay na hinabi', 'matibay na kwintas',
    'pulseras na gawa sa kamay', 'regalo sa kaarawan', 'regalo sa anibersaryo', 'pangkasal na alahas', 'abay na alahas',
    'natatanging disenyo', 'sariling disenyo', 'likhang joulery', 'tatak joulery', 'joulery pilipinas', 'joulery manila',
    'ala-ala ng pilipinas', 'ala-ala ng isla', 'alahas ng dagat', 'alahas ng bundok', 'katutubong sining', 'habing kamay',
    'habing pinoy', 'sinulid at hiyas', 'kristal na puti', 'kristal na lila', 'kristal na asul', 'alahas na pambabae',
    'alahas na panlalaki', 'regalo para sa nanay', 'regalo para sa asawa', 'regalo para sa kasintahan', 'murang alahas',
    'mamahaling alahas', 'eleganteng alahas', 'simpleng alahas', 'modernong alahas', 'tradisyonal na disenyo',
    'disenyong pilipino', 'likha ng kamay', 'sining ng paghabi', 'paghabi ng pangarap', 'joulery accessories pilipinas',
    'alahas na may kahulugan', 'alahas na may kwento', 'kwento ng artisan', 'suportahan ang lokal', 'bili ng lokal',
    'online shop pilipinas', 'tindahan ng alahas', 'tindahan ng kwintas', 'tindahan ng pulseras', 'mura at magandang alahas',
    'de-kalidad na alahas', 'totoong ginto', 'totoong pilak', 'totoong perlas', 'alahas na matibay', 'palamuti sa katawan',
    'palamuting pinoy', 'sining na naisusuot', 'hiyas ng katimugan', 'hiyas ng hilaga', 'hiyas ng gitna', 'perlas ng joulery',

    // --- English Set 2 (100+) ---
    'luxury lifestyle', 'editorial fashion', 'vogue jewelry', 'harpers bazaar jewelry', 'jewelry addict', 'jewelry lover',
    'jewelry obsessed', 'daily jewelry', 'layering necklaces', 'stackable bracelets', 'arm party', 'neck mess',
    'jewelry organizer', 'jewelry care', 'jewelry cleaning', 'ethical sourcing', 'conflict free gems', 'earth friendly jewelry',
    'small business jewelry', 'women owned business', 'female founder', 'artisan story', 'maker movement', 'slow fashion',
    'conscious consumer', 'capsule wardrobe jewelry', 'timeless elegance', 'vintage inspired', 'retro style jewelry',
    'futuristic jewelry', 'bold aesthetic', 'soft girl aesthetic', 'clean girl aesthetic', 'cottagecore jewelry',
    'dark academia jewelry', 'coastal grandmother jewelry', 'barbiecore jewelry', 'mermaids jewelry', 'ocean inspired',
    'nature inspired jewelry', 'floral jewelry', 'celestial jewelry', 'zodiac jewelry', 'birthstone jewelry',
    'protective crystals', 'healing stones', 'energy jewelry', 'meditation beads', 'yoga jewelry', 'spiritual jewelry',
    'wellness accessories', 'meaningful gifts', 'keepsake jewelry', 'heirloom quality', 'bespoke jewelry',
    'jewelry for her', 'jewelry for him', 'unisex jewelry', 'gender neutral accessories', 'travel jewelry',
    'lightweight jewelry', 'comfort fit', 'hypoallergenic jewelry', 'nickel free', 'sensitive skin jewelry',
    'wedding guest jewelry', 'graduation gift', 'mothers day gift', 'fathers day gift', 'valentines day gift',
    'christmas jewelry', 'holiday sparkle', 'new year jewelry', 'party accessories', 'festival jewelry',
    'rave jewelry', 'concert outfit jewelry', 'brunch style', 'work wear jewelry', 'office accessories',
    'zoom call jewelry', 'statement pieces', 'everyday luxury', 'affordable sparkle', 'investment jewelry',
    'jewelry collection launch', 'new arrivals jewelry', 'best selling jewelry', 'customer favorite jewelry',
    'top rated jewelry', 'jewelry reviews', 'jewelry unboxing', 'jewelry haul', 'jewelry flatlay',
    'jewelry photoshoot', 'jewelry videography', 'jewelry content creator', 'jewelry influencer', 'jewelry blogger',
    'jewelry styling tips', 'how to wear necklaces', 'how to wear bracelets', 'jewelry gift guide', 'luxury gifting'
  ],
};
