import { CollectionConfig } from 'payload';

export const Products: CollectionConfig = {
  slug: 'products',
  admin: {
    useAsTitle: 'name',
    defaultColumns: ['name', 'price', 'category', 'stock', 'ordersCount', 'viewsCount', 'totalRevenue', 'conversionRate', 'inventoryValue', 'averageRating'],
  },
  access: {
    read: () => true, // Anyone can see products
  },
  hooks: {
    beforeChange: [
      async ({ data, req, originalDoc }) => {
        const siteName = process.env.NEXT_PUBLIC_SITE_NAME || 'Joulery';
        
        if (!data.meta) data.meta = {};

        if (data.name && !data.meta.title) {
          data.meta.title = `${data.name} | ${siteName}`;
        }
        
        if (data.description && !data.meta.description) {
          data.meta.description = data.description.substring(0, 155) + (data.description.length > 155 ? '...' : '');
        }

        if (data.imageStill && !data.meta.image) {
          data.meta.image = data.imageStill;
        }

        // 1. Calculate Revenue & Inventory Value
        const price = data.price || 0;
        const orders = data.ordersCount || 0;
        const stock = data.stock || 0;
        const views = data.viewsCount || 0;

        data.totalRevenue = price * orders;
        data.inventoryValue = price * stock;

        // 2. Calculate Conversion Rate (capped at 100%)
        if (views > 0) {
          const rate = Math.min(100, Math.round((orders / views) * 100));
          (data as any).conversionRate = `${rate}%`;
        } else {
          (data as any).conversionRate = "0%";
        }

        // 3. Calculate Average Rating from embedded reviews array
        const reviewsList = data.reviews ?? (originalDoc as any)?.reviews ?? [];
        if (reviewsList.length > 0) {
          const sum = reviewsList.reduce((acc: number, rev: any) => acc + (Number(rev.rating) || 0), 0);
          data.averageRating = Number((sum / reviewsList.length).toFixed(1));
        } else {
          data.averageRating = 0;
        }

        return data;
      },
    ],
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
      index: true,
      admin: {
        description: 'Used for SEO-friendly URLs (e.g., aquamarine-silk-necklace)',
      },
    },
    {
      name: 'price',
      type: 'number',
      required: true,
    },
    {
      name: 'description',
      type: 'textarea',
      required: true,
    },
    {
      name: 'category',
      type: 'select',
      required: true,
      options: [
        { label: 'Necklace', value: 'necklace' },
        { label: 'Bracelet', value: 'bracelet' },
      ],
    },
    {
      name: 'stock',
      type: 'number',
      required: true,
      defaultValue: 10,
    },
    {
      name: 'ordersCount',
      type: 'number',
      required: true,
      defaultValue: 0,
      admin: {
        description: 'Used for sorting by "Best Selling"',
      },
    },
    {
      name: 'viewsCount',
      type: 'number',
      defaultValue: 0,
      admin: {
        description: 'Total number of times this product was viewed.',
        readOnly: true,
      },
    },
    {
      name: 'totalRevenue',
      type: 'number',
      defaultValue: 0,
      admin: {
        description: 'Total revenue generated by this product (Price x Orders).',
        readOnly: true,
      },
    },
    {
      name: 'conversionRate',
      type: 'text',
      defaultValue: '0%',
      admin: {
        description: 'Percentage of views that turned into orders.',
        readOnly: true,
      },
    },
    {
      name: 'inventoryValue',
      type: 'number',
      defaultValue: 0,
      admin: {
        description: 'Current market value of remaining stock (Price x Stock).',
        readOnly: true,
      },
    },
    {
      name: 'averageRating',
      type: 'number',
      defaultValue: 0,
      admin: {
        description: 'Average customer rating based on reviews.',
        readOnly: true,
      },
    },
    {
      name: 'imageStill',
      type: 'upload',
      relationTo: 'media',
      required: true,
      admin: {
        description: 'Product still shot (usually no-bg)',
      },
    },
    {
      name: 'imageWorn',
      type: 'upload',
      relationTo: 'media',
      required: true,
      admin: {
        description: 'Lifestyle or worn shot',
      },
    },
    {
      name: 'gallery',
      type: 'array',
      label: 'Extra Photos (Optional)',
      fields: [
        {
          name: 'image',
          type: 'upload',
          relationTo: 'media',
          required: true,
        },
      ],
      admin: {
        description: 'Add more detail shots to show off the craftsmanship.',
      },
    },
    {
      name: 'video',
      type: 'upload',
      relationTo: 'media',
      label: 'Product Video (Optional)',
      admin: {
        description: 'Upload a short video or cinemagraph of the piece.',
      },
    },
    {
      name: 'meta',
      type: 'group',
      label: 'SEO / Meta Data',
      fields: [
        {
          name: 'title',
          type: 'text',
          label: 'Meta Title',
        },
        {
          name: 'description',
          type: 'textarea',
          label: 'Meta Description',
        },
        {
          name: 'image',
          type: 'upload',
          relationTo: 'media',
          label: 'Meta Preview Image (OG Image)',
        },
      ],
    },
    {
      name: 'reviews',
      type: 'array',
      fields: [
        {
          name: 'author',
          type: 'text',
          required: true,
        },
        {
          name: 'rating',
          type: 'number',
          required: true,
          min: 1,
          max: 5,
          admin: {
            description: 'Enter a rating between 1 and 5.',
          },
        },
        {
          name: 'date',
          type: 'date',
          required: true,
          admin: {
            date: {
              pickerAppearance: 'dayOnly',
              displayFormat: 'MMM d, yyyy',
            },
          },
        },
        {
          name: 'content',
          type: 'textarea',
          required: true,
        },
      ],
    },
  ],
};
